graphql:
  packages:
    - "com.graphql.model"
  subscriptions:
    # Send a ka message every 1000 ms (1 second)
    keepAliveInterval: 1000
jwt-security:
  secret: PseudoSecret-Pseudosecret-Please-Use-Ur-Own-Key-PseudoSecret-Pseudosecret
  expiration-time: 365
server:
  compression:
    enabled: false
  http2:
    enabled: true
  port: 4080
  servlet:
    context-path: /graphql
